name = "MultiScaleArrays"
uuid = "f9640e96-87f6-5992-9c3b-0743c6a49ffa"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]
version = "1.16.0"

[deps]
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
OrdinaryDiffEqCore = "bbf590c4-e513-4bbe-9b18-05decba2e5d8"
OrdinaryDiffEqDifferentiation = "4302a76b-040a-498a-8c04-15b101fed76b"
OrdinaryDiffEqRosenbrock = "43230ef6-c299-4910-a778-202eb28ce4ce"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StochasticDiffEq = "789caeaf-c7a9-5a7d-9973-96adeb23e2a0"

[weakdeps]
SparseDiffTools = "47a9eef4-7e08-11e9-0b38-333d64bd3804"

[extensions]
MultiScaleArraysSparseDiffToolsExt = "SparseDiffTools"

[compat]
DiffEqBase = "6.5"
DifferentiationInterface = "0.7.7"
FiniteDiff = "2.3"
ForwardDiff = "0.10"
OrdinaryDiffEq = "6"
OrdinaryDiffEqCore = "1.30.0"
OrdinaryDiffEqDifferentiation = "1.16"
OrdinaryDiffEqRosenbrock = "1.17.0"
RecursiveArrayTools = "1,2,3"
SciMLBase = "2.116"
SparseDiffTools = "1.6, 2"
Statistics = "1"
StochasticDiffEq = "6.13"
julia = "1.10"

[extras]
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["OrdinaryDiffEq", "SafeTestsets", "Test"]
